New Component: Camera
gore-engine/gore pull request #27
Opened 2024-01-10 14:04 UTC by MarshallW906

Implement a very simple `Camera : public Component`, which accepts and preserves `fov`, `aspect ratio`, `zNear`, `zFar`, `Perspective/Orthographic`, and produce view and projection matrices (v, p, vp)

These are also changed when implementing `Camera`:
1. Implement Transform::Get{Local<=>World}Matrix with/without scale, using `rtm::qvv` and `rtm::qv` which saves the expensive cost from direct matrix inverse
2. Change `Component::m_GameObject` and `m_Started` to protected, so that `Camera` will have access and hence `m_GameObject->transform`

2024-01-11 06:09 UTC, shurunxuan requested changes
Something is wrong. See `test_camera` branch.

2024-01-11 06:09 UTC, shurunxuan commented on src/Object/Component.h
>      bool m_Started;
Let's keep `m_Started` private. It controls if `Start()` is called and should not be accessed by actual components.

2024-01-11 06:09 UTC, shurunxuan commented on src/Object/Camera.inl
> +float Camera::GetFOV() const
These functions are not marked with `inline`. I would say either put these implementations inside the header file directly or in a source file, instead of abusing `.inl`.

2024-01-11 06:09 UTC, shurunxuan commented on src/Object/Camera.inl
> +float Camera::GetFOV() const
There are also `inconsistent dll linkage` warnings emitted from MSVC for these functions.

2024-01-11 06:09 UTC, shurunxuan commented on src/Object/Camera.h
> +    explicit Camera(GameObject * gameObject, ProjectionType projectionType = ProjectionType::Perspective, float fov = 60.0f, float AspectRatio = 16.0f / 9.0f, float near = 0.1f, float far = 1000.0f)
We currently do not have any way of forwarding parameters from AddComponent<> to actual constructor, so any parameters except GameObject* are not useful for now. Also, I'd say put this implementation inside `.cpp` file.

2024-01-11 06:09 UTC, shurunxuan commented on src/Object/Camera.h
> +    void SetNear(float near);
I think Windows.h is defining `near` and `far`. We need to undef these macros in this header in case they are included after Windows.h.

2024-01-11 06:11 UTC, shurunxuan commented on src/Object/Camera.inl
> +float Camera::GetFOV() const
> There are also `inconsistent dll linkage` warnings emitted from MSVC for these functions.

It doesn't show on CI results, but does on my local machine.

2024-01-11 06:26 UTC, MarshallW906 commented on src/Object/Camera.h
> +    explicit Camera(GameObject * gameObject, ProjectionType projectionType = ProjectionType::Perspective, float fov = 60.0f, float AspectRatio = 16.0f / 9.0f, float near = 0.1f, float far = 1000.0f)
Previously I added a function `Component::SelfOrDerivedTypePointer<T> GameObject::AddComponent(T* component)` which allows users to create component on their own before adding them to any game objects. 

It still has a use case under this condition

2024-01-11 07:33 UTC, shurunxuan commented on src/Object/Camera.h
> +    explicit Camera(GameObject * gameObject, ProjectionType projectionType = ProjectionType::Perspective, float fov = 60.0f, float AspectRatio = 16.0f / 9.0f, float near = 0.1f, float far = 1000.0f)
The problem with this approach is that the components added to a GameObject will be destroyed by the GameObject when the object is destroyed, but we will have no means of knowing how the component provided by the user is allocated, for example if it's `new` or `malloc` or any other custom allocator.

I think the proper way to call a non-standard constructor (constructors with more parameters than just the GameObject pointer) is to use a variadic template constructor to forward the arguments, something like what `std::make_shared` does.

2024-01-11 07:48 UTC, MarshallW906 commented on src/Object/Component.h
>      bool m_Started;
Okay, change submitted

2024-01-12 05:32 UTC, MarshallW906 commented on src/Object/Camera.inl
> +float Camera::GetFOV() const
You are right. I have them moved into `.h` and renamed more clearly.

2024-01-12 05:33 UTC, MarshallW906 commented on src/Object/Camera.h
> +    void SetNear(float near);
I find dealing with these macros very disappointing. Now I use `ZMin` and `ZMax` instead

2024-01-12 05:35 UTC, MarshallW906 commented on src/Object/Camera.h
> +    explicit Camera(GameObject * gameObject, ProjectionType projectionType = ProjectionType::Perspective, float fov = 60.0f, float AspectRatio = 16.0f / 9.0f, float near = 0.1f, float far = 1000.0f)
Okay. For simplicity I replaced the multi-parameter constructor with a single-parameter one

2024-01-12 05:38 UTC, MarshallW906 commented
what?

2024-01-12 06:10 UTC, shurunxuan approved these changes

2024-01-12 08:19 UTC, merged